namespace SocietyLedger.Domain.Entities
{
    /// <summary>
    /// Base entity class following DDD best practices.
    /// Contains common properties for all domain entities.
    /// </summary>
    public abstract class BaseEntity
    {
        /// <summary>
        /// Internal database identifier. Should never be exposed in APIs.
        /// </summary>
        public long Id { get; protected set; }

        /// <summary>
        /// Public identifier using GUID Version 7 (time-ordered).
        /// This should be used in all API endpoints for security and external references.
        /// </summary>
        public Guid PublicId { get; protected set; }

        /// <summary>
        /// UTC timestamp when the entity was created.
        /// </summary>
        public DateTime CreatedAt { get; protected set; }

        /// <summary>
        /// UTC timestamp when the entity was last updated.
        /// </summary>
        public DateTime UpdatedAt { get; protected set; }

        /// <summary>
        /// Protected constructor to enforce invariants and encapsulation.
        /// PublicId is generated by database default (gen_random_uuid()).
        /// Audit timestamps are set by database defaults.
        /// </summary>
        protected BaseEntity()
        {
            // Don't set PublicId here - let database default generate it
            // Don't set timestamps - let database defaults handle them
        }

        /// <summary>
        /// Updates the UpdatedAt timestamp. Should be called before saving changes.
        /// </summary>
        public virtual void MarkAsUpdated()
        {
            UpdatedAt = DateTime.UtcNow;
        }

        /// <summary>
        /// Sets the PublicId explicitly. Used by EF Core when loading from database.
        /// </summary>
        internal void SetPublicId(Guid publicId)
        {
            PublicId = publicId;
        }

        /// <summary>
        /// Sets the Id explicitly. Used by EF Core when loading from database.
        /// </summary>
        internal void SetId(long id)
        {
            Id = id;
        }
    }
}
